/**
 * @module proactive
 * Data models for the Proactive_Intelligence_Service.
 *
 * The Proactive_Intelligence_Service anticipates End_User needs and delivers
 * timely suggestions subject to interrupt budget constraints, focus detection,
 * and signal scoring.
 *
 * @see Requirement 39.1
 */

import type { UnitScore } from './branded.js';

/**
 * An anticipatory suggestion generated by the Proactive_Intelligence_Service.
 * Signals are scored by urgency, relevance, and recency to determine whether
 * they should be delivered to the user.
 */
export interface ProactiveSignal {
  /** Unique identifier for this signal */
  readonly signal_id: string;

  /** Source of the signal, e.g. "calendar", "habit", "error_detection", "focus_break" */
  readonly source: string;

  /** How urgent this signal is in [0.0, 1.0]; values > 0.9 can override interrupt budget */
  readonly urgency: UnitScore;

  /** How relevant this signal is to the user's current context in [0.0, 1.0] */
  readonly relevance: UnitScore;

  /** Recency decay factor in [0.0, 1.0]; older signals decay toward 0 */
  readonly recency_factor: UnitScore;

  /** Composite score: urgency * relevance * recency_factor */
  readonly computed_score: UnitScore;

  /** The suggestion content to present to the user */
  readonly content: string;

  /** ISO 8601 timestamp when this signal was generated */
  readonly timestamp: string;
}

/**
 * Current status of the interrupt budget for a given principal.
 * The budget limits proactive interruptions to a configurable maximum per hour
 * (default 2), exceeded only when urgency > 0.9.
 */
export interface InterruptBudgetStatus {
  /** The principal whose budget this represents */
  readonly principal_id: string;

  /** Number of interruptions delivered in the current hour */
  readonly current_hour_count: number;

  /** Maximum interruptions allowed per hour (default 2) */
  readonly max_per_hour: number;

  /** Minimum computed_score required for delivery */
  readonly score_threshold: number;

  /** Accumulated threshold adjustment from user dismissals (positive = stricter) */
  readonly session_threshold_adjustment: number;

  /** ISO 8601 timestamp of the last delivered signal, if any */
  readonly last_delivery_timestamp?: string;
}

/**
 * The outcome of evaluating whether a proactive signal should be delivered
 * to the user or suppressed.
 */
export interface DeliveryDecision {
  /** The signal that was evaluated */
  readonly signal_id: string;

  /** Whether the signal was delivered or suppressed */
  readonly decision: 'delivered' | 'suppressed';

  /** Reason for suppression, e.g. "budget_exceeded", "deep_focus", "below_threshold" */
  readonly reason?: string;

  /** ISO 8601 timestamp when this decision was made */
  readonly timestamp: string;
}
